avp_net_stats return value change in 4.11
avp_net.c:630:21: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
  .ndo_get_stats64 = avp_net_stats,
                     ^~~~~~~~~~~~~

Signed-off-by: Jan Zizka <jan.zizka@nokia.com>
Signed-off-by: Tommi Rantala <tommi.t.rantala@nokia.com>